baseURL = 'https://bb82.netlify.app/'
languageCode = 'fr-fr'
title = 'BB82'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["json"]


[outputFormats]
  [outputFormats.json]
    mediaType = "application/json"
  [outputFormats.Agenda]
    mediaType = "application/json"
    baseName = "json/agenda" 
    isPlainText = true
  

[outputs]
page=["HTML"]


[menu]
  [[menu.main]]
    identifier = "accueil"
    name = "Accueil"
    url = "/"
    weight = 1    
  [[menu.main]]
    identifier = "apropos"
    name = "À propos"
    url = "/apropos"
    weight = 10
  [[menu.main]]
    identifier = "bricotek"
    name = "Bricotek"
    url = "/bricotek"
    weight = 20
  [[menu.main]]
    identifier = "agenda"
    name = "Agenda"
    url = "/agenda"
    weight = 30
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 40
